// Project list

export default [
  {
    id: 1,
    title: "React Portfolio Site",
    image: "/images/projects/pr01.png",
    techs: ["React", "NextJS", "TailwindCSS"],
    description: "React Portfolio Site with Theme Switching",
    githubLink: "https://github.com/husse-akan/chas-portfolio",
    mainpage: true,
  },
  {
    id: 2,
    title: "React Components Library",
    image: "/images/projects/pr06.png",
    techs: ["React", "Vite", "Tailwind", "React Router"],
    description: "Created a component library with React.",
    githubLink: "https://github.com/husse-akan/react_components",
    mainpage: true,
  },
  {
    id: 3,
    title: "React Clock",
    image: "/images/projects/pr04.png",
    techs: ["React", "Vite"],
    description: "Builded some cities clock & timer with React.",
    githubLink: "https://github.com/husse-akan/chas_react-clock",
    mainpage: true,
  },
  {
    id: 4,
    title: "Sveriges Radio Player in React",
    image: "/images/projects/pr02.png",
    techs: ["React", "Vite"],
    description: "Created radio player with use React and Sveriges Radio's API",
    githubLink: "https://github.com/husse-akan/radioplayer_react",
    mainpage: false,
  },
  {
    id: 5,
    title: "React Todo List",
    image: "/images/projects/pr03.png",
    techs: ["React", "Vite"],
    description: "Created ToDo list with use React",
    githubLink: "https://github.com/husse-akan/chas-todolist",
    mainpage: false,
  },
  {
    id: 6,
    title: "Dashboard with Radix UI",
    image: "/images/projects/pr05.png",
    techs: ["React", "Vite, Radix UI"],
    description: "Created a dashboard with React & Radix UI",
    githubLink: "https://github.com/husse-akan/chas_radix",
    mainpage: false,
  },
  {
    id: 7,
    title: "Redesign Zoom's Website",
    image: "/images/projects/pr-zoom.png",
    techs: ["JS", "Vite", "Tailwind CSS"],
    description: "Redesign Zoom website with Tailwind CSS.",
    githubLink: "https://github.com/husse-akan/chas_zoom",
    mainpage: false,
  },
  {
    id: 8,
    title: "Redesign Tailwind Website",
    image: "/images/projects/pr-tailwind.png",
    techs: ["JS", "Vite", "Tailwind CSS"],
    description: "Redesign Tailwind CSS website with Tailwind CSS :)",
    githubLink: "https://github.com/husse-akan?tab=repositories",
    mainpage: false,
  },
];
